### ISSUE TITLE
first example crashes when starting Julia with multiple threads on apple silicon

### ISSUE THREAD

**Issue by ericphanson** [Clemapfel/mousetrap.jl#10]
```julia
In [2]: versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE = eager

(@mousetrap) pkg> st
Status `~/.julia/environments/mousetrap/Project.toml`
  [5deeb4b9] mousetrap v0.1.0 `https://github.com/Clemapfel/mousetrap.jl#main`
  [7f2654e2] mousetrap_apple_jll v0.1.0+0 `https://github.com/Clemapfel/mousetrap_apple_jll#main`
  [b6bb2801] mousetrap_linux_jll v0.1.0+0 `https://github.com/Clemapfel/mousetrap_linux_jll#main`
  [1923bf96] mousetrap_windows_jll v0.1.0+0 `https://github.com/Clemapfel/mousetrap_windows_jll#main`

In [4]: using mousetrap

In [5]: main() do app::Application
            window = Window(app)
            set_child!(window, Label("Hello World!"))
            present!(window)
        end

(process:93174): mousetrap.jl-WARNING **: 17:33:46.903: In mousetrap.main: You are running mousetrap from within the REPL. Interactive use of mousetrap is an experimental feature, side-effects may occurr.
Out[5]: Task (runnable) @0x000000010e68a590

In [6]:
(<unknown>:93174): GLib-GIO-CRITICAL **: 17:33:47.332: g_settings_schema_source_lookup: assertion 'source != NULL' failed

(<unknown>:93174): GLib-GIO-CRITICAL **: 17:33:47.332: g_settings_schema_source_lookup: assertion 'source != NULL' failed
2023-08-20 17:33:47.392 julia[93174:85063167] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
)
libc++abi: terminating with uncaught exception of type NSException

[93174] signal (6): Abort trap: 6
in expression starting at none:0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 5301661 (Pool: 5298319; Big: 3342); GC: 8
zsh: abort      julia
```

If I start Julia with
```julia
JULIA_NUM_THREADS=1 julia
```
then the example works, although it doesn't render as nicely as in the README screenshot.
<img width="359" alt="Screen Shot 2023-08-20 at 17 35 47" src="https://github.com/Clemapfel/mousetrap.jl/assets/5846501/e78ea595-4fcb-477e-aace-a44d0ece18de">

**Comment by Clemapfel** [comment]
Thank you, could you run the following code and tell me if it still crashes?

```julia
using mousetrap
app = Application("issue.test")
connect_signal_activate!(app) do app::Application
    window = Window(app)
    set_child!(window, Label("Test")
    present!(window)
 end
 ```
 
 I will also try to reproduce this on my end

**Comment by ericphanson** [comment]
> Thank you, could you run the following code and tell me if it still crashes?

This doesn't not crash. No window pops up though. (BTW: I added a close-paren to the  line `set_child!(window, Label("Test")`)

**Comment by Clemapfel** [comment]
Yes thank you, I typo'd there.

I'm almost positive what is causing this then, I'll make a PR very soon. It's most likely due to the usage of `Task` [here](https://github.com/Clemapfel/mousetrap.jl/blob/main/src/mousetrap.jl#L1579).

Until then, if you want, you could try exploring mousetrap more by just using the code I posted (minus the typo), it looks more complicated but it's functionally equivalent to `main`. Just put anything that you would've put into main into the signal handler (the function after `do app::Application`).

**Comment by ericphanson** [comment]
That works! It opens a window and does not crash.
<img width="388" alt="Screen Shot 2023-08-22 at 00 47 53" src="https://github.com/Clemapfel/mousetrap.jl/assets/5846501/e6699511-000e-45f0-96da-875c46880e9f">

**Comment by Clemapfel** [comment]
Okay thank you, I'm pretty sure usage of `Threads.Task` [here](https://github.com/Clemapfel/mousetrap.jl/blob/main/src/mousetrap.jl#L1579) is causing this then. I'll have a PR ready as soon as possible. 

Until then you can just use that code snippet instead of `main`. Thank you for helping out!
