### ISSUE TITLE
Consider renaming the package

### ISSUE THREAD

**Issue by ufechner7** [Clemapfel/mousetrap.jl#12]
Julia packages usually start with a capital letter. Furthermore a name that indicates the functionality is also nice to have.

So perhaps rename it it to MousetrapGUI or something similar?

**Comment by Clemapfel** [comment]
I disagree on the GUI suffix, genie, gtk, electron, skia, etc. don't have GUI in the name.
Making the package name uppercase is reasonable though, I think I will do the change when the package is registered.

**Comment by Clemapfel** [comment]
Renamed by https://github.com/Clemapfel/mousetrap.jl/commit/f8f1055ab84bb7014df5f0de338e738f2647d213, which will be published with 0.2.0 in the next few days. Thank you for the suggestion!
