### ISSUE TITLE
Mousetrap not found

### ISSUE THREAD

**Issue by trukker41** [Clemapfel/Mousetrap.jl#30]
In julia REPL
] Pkg add Mousetrap
error
Mousetrap (not found in project, manifest or registry)
julia 1.9.3
Windows 11

**Comment by Clemapfel** [comment]
Mousetrap v0.2.0 needs to be installed according to the readme and document, see [here](https://github.com/clemapfel/mousetrap.jl#installation)

```julia
import Pkg
begin
    try Pkg.rm("mousetrap") catch end
    Pkg.add(url="https://github.com/Clemapfel/mousetrap_windows_jll")
    Pkg.add(url="https://github.com/Clemapfel/mousetrap_linux_jll")
    Pkg.add(url="https://github.com/Clemapfel/mousetrap_apple_jll")
    Pkg.add(url="https://github.com/Clemapfel/mousetrap.jl")
end
```

0.3.0 is in the process of being registered but 0.2.0 is not currently, so you need to run the above code instead.

**Comment by trukker41** [comment]
Thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
