### ISSUE TITLE
Menu not rendering text on Windows

### ISSUE THREAD

**Issue by jarredclloyd** [Clemapfel/Mousetrap.jl#41]
Hello, great work on this project. This may just be something I'm doing, but I cannot get a menubar to correctly render the labels on Windows. 
Screenshot below shows the code, and then two instances of the GUI. The slightly smaller one is the one running on Windows where the labels "File" and "Help" are not rendered as such. The second is an instance running on WSLG - Ubuntu where it renders correctly, at the same time.
I did try adding a custom CSS after to see if it was just an issue with the default font, but it did not change.
![image](https://github.com/Clemapfel/Mousetrap.jl/assets/74882990/8abd0ab1-0100-4387-beef-a8543f6d9eab)

PS. Is there a way to detect the user's default OS theme? I.e. is light/dark/high contrast by default?

**Comment by Clemapfel** [comment]
Hi, I'm pretty sure this is a font issue. Please add:

```julia
add_css!("""
 label {
    font-family: monospace;
 }
 """)
 ```
 Inside your `main` and see if that causes the menu font to show up (except in monospace). If yes, than that means that that Windows default font is somehow not being read correctly, it's not available in a certain size or style, or there's no font fallback. What font are you using exactly? I can't reproduce this on my windows machine.

> Is there a way to detect the user's default OS theme? I.e. is light/dark/high contrast by default?
The value returned by `get_current_theme` at the start of runtime is the value the users OS prefers. After changing the theme with `set_current_theme!`, you're unable to access the default value, so you need to store it on startup.

**Comment by jarredclloyd** [comment]
Sorry about the delayed response. I have done a bit more testing and using css to theme it as suggested. 
It appears to be a font size issue/style on windows. If I use a small tag
`theme_label_box = hbox(Label("<small>LIGHT</small>"), Label("/"), Label("DARK"))` with the default font, I get non-rendered text. 
If I set the font size to say 11 px or less manually via a css class and the font to monospace, Arial, or use the default font (no font family css) is also doesn't render.
If I use a font class with Open Sans or just Sans it renders fine at 11 px or less.

The following code:
`using Mousetrap
function set_accent_color!(color::RGBA)
    return add_css!("@define-color accent_bg_color $(serialize(color));")
end
add_css!("""
 .OpenSans {
    font-family: Open Sans;
 }
 """)
add_css!("""
.small {
   font-size: 11px;
}
""")
add_css!("""
 .mono {
    font-family: monospace;
 }
 """)

main() do PlasmaTraceGUI::Application
    # Main application window

    PlasmaTraceMainWindow = Window(PlasmaTraceGUI)
    PlasmaTraceHeaderMain = get_header_bar(PlasmaTraceMainWindow)
    os_theme = get_current_theme(PlasmaTraceGUI)
    set_accent_color!(RGBA(0.75, 0, 1, 1))
    current_theme = deepcopy(os_theme)

    # Header Bar customisation
    # Menu bar
    PlasmaTraceMainMenu = MenuModel()
    file_submenu = MenuModel()
    close_application = Action("file.close", PlasmaTraceGUI) do x::Action
        return close!(PlasmaTraceMainWindow)
    end
    add_action!(file_submenu, "Exit", close_application)

    help_submenu = MenuModel()

    add_submenu!(PlasmaTraceMainMenu, "File", file_submenu)
    add_submenu!(PlasmaTraceMainMenu, "Help", help_submenu)

    menubar = MenuBar(PlasmaTraceMainMenu)
    push_front!(PlasmaTraceHeaderMain, menubar)

    # Light/Dark theme toggle switch, add to header
    set_title!(PlasmaTraceMainWindow, "PlasmaTrace 0.0.1-DEV")
    theme_toggle = Switch()
    if current_theme == Theme(THEME_DEFAULT_LIGHT)
        set_is_active!(theme_toggle, false)
    else
        set_is_active!(theme_toggle, true)
    end
    theme_label_box = hbox(Label("LIGHT"), Label("/"), Label("DARK"))
    theme_box = vbox(theme_toggle, theme_label_box)
    push_back!(PlasmaTraceHeaderMain, theme_box)
    set_tooltip_text!(theme_toggle, "Light theme | Dark theme")
    connect_signal_switched!(theme_toggle) do self::Switch
        return if get_is_active(theme_toggle) == true
            set_current_theme!(PlasmaTraceGUI, THEME_DEFAULT_DARK)
        else
            set_current_theme!(PlasmaTraceGUI, THEME_DEFAULT_LIGHT)
        end
    end

    left = Label("LEFT")
    set_margin_start!(left, 10)

    center = Label("CENTER")
    set_margin_horizontal!(center, 10)

    right = Label("RIGHT")
    set_margin_end!(right, 10)

    # create a horizontal box
    box = Box(ORIENTATION_HORIZONTAL)

    # add `left` to the start
    push_front!(box, left)

    # add `right to the end
    push_back!(box, right)

    # insert `center` after `left`
    insert_after!(box, center, left)

    # add box to window
    set_child!(PlasmaTraceMainWindow, box)

    add_css_class!(PlasmaTraceHeaderMain, "mono")
    add_css_class!(theme_box, "small")
    add_css_class!(left, "mono")
    add_css_class!(left, "small")
    add_css_class!(right, "OpenSans")

    present!(PlasmaTraceMainWindow)
end`

Produces the results in the attached image
![image](https://github.com/Clemapfel/Mousetrap.jl/assets/74882990/60a6a314-a8b8-4fbe-b5bc-637bf732db9b)
With the lower GUI being run on WSLg(Ubuntu), and the upper image the Windows version.

**Comment by Clemapfel** [comment]
I don't fully understand. What you are saying is that the default font or Arial fails to render at 11px or smaller, but does render at larger sizes, while the OpenSans font render at any size?

I'm pretty sure this isn't a Mousetrap issue then, your default font and Arial don't seem to be available at that size. 

I'll try to reproduce this with Arial on my windows machine and if it also fails, I'll ask with the GTK people.

**Comment by jarredclloyd** [comment]
Thanks for following this up. I definitely don't intend on using such a small font size, because as you say, it is a big accessibility issue. 
It was more that I came across the issue when testing out the <small> tag while learning how to use mousetrap/develop a GUI.

Many thanks for your help, and awesome development efforts.
