### ISSUE TITLE
Gtk4LayerShell

### ISSUE THREAD

**Issue by tiagocpontesp** [Clemapfel/Mousetrap.jl#73]
I'd like to setup some desktop widgets on wayland, but i'm out of my comfort zone. 
Wondering how to go about it:
- is gtk-layer-shell supported?
- if not -- is it in scope?
Best.

**Comment by Clemapfel** [comment]
I have no experience with gtk-layer-shell, but Mousetrap mostly abstracts all the GTK interfaces often omitting big parts of it, so I don't think it will be possible, sorry
