### ISSUE TITLE
need example of using an external file

### ISSUE THREAD

**Issue by JeffreySarnoff** [Clemapfel/mousetrap.jl#8]
```
(process:54764): mousetrap.jl-WARNING **: 06:38:38.015: In mousetrap.main: You are running mousetrap from within the REPL. Interactive use of mousetrap is an experimental feature, side-effects may occurr.
Task (runnable) @0x00000238189bb080
```

**Comment by Clemapfel** [comment]
[In the documentation](http://clemens-cords.com/mousetrap/01_manual/01_installation/#Hello-World), it says (quote)

To create our first mousetrap app, we create a Julia file main.jl, with the following contents:
  
```julia
using mousetrap
main() do app::Application
    window = Window(app)
    set_child!(window, Label("Hello World!"))
    present!(window)
end
```

To start our app, we navigate to the location of main.jl in our console, then execute:

```
# in same directory as `main.jl`
julia main.jl
```

Go into your console and run the file using `julia main.jl`, where `main.jl` is the filename
